package com.filipemorgado.myexpenses.utilities

const val TAG_HOME_VIEW_MODEL = "TAG_HOME_VIEW_MODEL"
const val TAG_HOME_FRAGMENT = "TAG_HOME_FRAGMENT"
const val TAG_EXPENSE_FRAGMENT = "TAG_EXPENSE_FRAGMENT"
const val TAG_TRANSACTION_ADAPTER = "TAG_TRANSACTION_ADAPTER"
const val TAG_TRANSACTION_VIEW_HOLDER = "TAG_TRANSACTION_VIEW_HOLDER"